### ISSUE TITLE
Containerize?

### ISSUE THREAD

**Issue by yet-another-account** [nuriel77/iri-playbook#63]
It would be nice if this were to be containerized.

**Comment by nuriel77** [comment]
@eukaryote31 I did that for IRI+Nelson, can be found here:
https://github.com/SemkoDev/nelson.cli/tree/master/contrib/ansible-playbook
Downside is that is doesn't include all the goodies that iri-playbook provides.

I'll be glad to see contributions to the playbook though.

**Comment by nuriel77** [comment]
If anyone is going to take the tasks of containerizing the playbook, it is worth noting that the iri-playbook delivers a complete full-node solution.
This includes a full system configuration. Having the services (iri, prometheus, iota exporter etc) in docker containers will still required some configuration on the system itself, e.g.:
- Systemd services to control to containers
- Docker (of course)
- Firewall configuration
- External DB paths (iota prom exporter, nelson and IRI)
- External configuration file paths.
etc.

**Comment by nuriel77** [comment]
This is the list of services that would have to run in containers:

- [x] haproxy
- [x] iota-prom-exporter
- [x] field
- [x] field expoter
- [x] node exporter
- [x] nelson.cli
- [x] nelson.gui
- [x] prometheus
- [x] alertmanager
- [x] grafana
- [x] IRI
- [x] iota peer manager

**Comment by pulento** [comment]
I just installed on a Bionic LXC and had to hack atop installation since atopacctd won't run inside a container. It seems to be running (haven't finished to download DB) since every process is up and running and I suppose that atop is just for console process monitoring with can be done with other means in container.

Anyway I'm a complete noob on ansible stuff but going to see if I can turn that atop as an optional for people who want to run inside a LXC the whole stuff.

Thanks

**Comment by nuriel77** [comment]
Started working on migrating the services into Docker.
If you would like to follow progress:
https://github.com/nuriel77/iri-playbook/pull/90

Contributions are always welcome.

**Comment by nuriel77** [comment]
Containerized version is working well.
There are some small issues however, that will hopefully get fixed in time:
* UDP peering becomes a problem if docker changes the source port. See https://github.com/iotaledger/iri/issues/961
* At time of writing, DevIOTA Field docker image is still untagged and latest version is 0.1.7 which is referencing the older .carriota-field secret file.
* This version may use more resources (memory and RAM)
